- name: Common setting up
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Install common
      include_role:
        name: common

- name: Enable & start sshd
  systemd:
    name: sshd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Enable & start ssh
  systemd:
    name: ssh
    state: restarted
    enabled: yes
    daemon_reload: yes