- name: Update apt cache
  apt:
    update_cache: yes

- name: Apt packages
  apt:
    name: ['curl', 'git', 'apt-transport-https', 'gnupg2', 'python', 'openssh-server', 'apt-transport-https']
    update_cache: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH
    
- name: Enable & start sshd
  systemd:
    name: sshd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Enable & start ssh
  systemd:
    name: ssh
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Remove k8s/git
  file:
    path: /k8s/git
    state: absent

- git:
    repo: 'https://github.com/GenzaStepan/K8s.git'
    dest: /k8s/git
    clone: yes
    update: yes

- name: Create create-config
  template:
    src: create-config.sh.tmpl
    dest: /k8s/create-config.sh

- name: Changing perm of "/create-config.sh", adding "+x"
  file:
    path: /k8s/create-config.sh
    mode: +x

- name: Create kubeadm init yaml
  shell: ./create-config.sh kubeadm
  args:
    chdir: /k8s

- name: "Remove swap device(s) from /etc/fstab"
  mount:
    src: '{{ item }}'
    path: none
    fstype: swap
    backup: yes
    state: absent
  with_items: '{{ swapdevs.stdout_lines }}'
  when: 'swapdevs.stdout_lines |length > 0'

- name: Disable swap
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0